name: yourturn
description: Local P2P turn-notifier skeleton for tabletop games (Flutter)
publish_to: 'none'
version: 0.0.4+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  uuid: ^4.4.0
  wakelock_plus: ^1.2.5
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0

flutter:
  uses-material-design: true
